/* Generated by gbrecomp */
#ifndef gbcamera_H
#define gbcamera_H

#include "gbrt.h"

const GBConfig* gbcamera_default_config(void);
void gbcamera_run(GBContext* ctx);
void gbcamera_init(GBContext* ctx);
int gbcamera_main(int argc, char* argv[]);

#endif
